name: EpyCubeApi
version: ${project.version}
author: Dinnerwolph
main: net.euphalys.core.api.EuphalysApi
commands:
  info:
    description: Avoir des informations sur les sanctions d'un joueur
  closechat:
    description: Fermer localement le chat
  openchat:
    description: Ouvrir localement le chat
  clearchat:
    description: Nettoyer localement le chat
  spectator:
    description: Se mettre en mode spectateur
  inv:
    description: Consulter l'inventaire d'un joueur
  tphere:
    description: TP Force à soi un joueur
  kill:
    description: Tuer un joueur
  rtp:
    description: Téléportation random à un joueur
  freeze:
    description: Rendre immobile un joueur
  vanish:
    description: Se rendre invisible
  speed:
    description: Améliorer sa rapidité §9Entre 1 et 10
  cps:
    description: Consulter les CPS d'un joueur
  closereport:
    description: Fermer un report
  listreport:
    description: Lister les reports
  inforeport:
    description: Lire les informations sur un report
  group:
    description: Commande administrative concernant les groupes utilisateurs
  nick:
  cl:
  aal:
  sal: